apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata: # kpt-merge: amf-example/amf-example
  name: amf-example
  namespace: amf-example
  annotations:
    internal.kpt.dev/upstream-identifier: "workload.nephio.org|NFDeployment|amf-example|amf-example"
spec:
  provider: amf.free5gc.io
## i guess tutaj...?
